..

diff --git a/.github/workflows/baseimages.yml b/.github/workflows/baseimages.yml
--- a/.github/workflows/baseimages.yml
+++ b/.github/workflows/baseimages.yml
@@ -59,6 +59,7 @@ env:
   BASE_DIR: baseimages
   PROJECT_DIR_DEPTH: 2
   DEFAULT_TERRAFORM_VERSION: 1.3.3
+  TERRAGRUNT_VERSION: v0.39.2
 
 defaults:
   run:
@@ -83,9 +84,17 @@ jobs:
       - name: Get PR number on push
         id: get_pr_number
         if: ${{ github.event_name == 'push' }}
-        uses: jwalton/gh-find-current-pr@v1.3.2
-        with:
-          state: all
+        run: |
+          pr_number=$(curl -sS \
+            -H "Accept: application/vnd.github+json" \
+            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
+            https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/pulls \
+            | jq -r '.[0].number')
+          if [[ $pr_number == "null" ]]; then
+            echo "Could not find PR number for commit=${{ github.sha }}"
+            exit 1
+          fi
+          echo ::set-output name=pr::${pr_number}
 
       # for workflow dispatch, check valid project specified
       - name: Validate workflow dispatch
@@ -117,9 +126,23 @@ jobs:
       - name: Get list of committed files
         id: files
         if: ${{ github.event_name == 'pull_request' || github.event_name == 'push' }}
-        uses: jitterbit/get-changed-files@v1
-        with:
-          format: 'space-delimited'
+        run: |
+          if [[ "${GITHUB_EVENT_NAME}" == "pull_request" ]]; then
+            pr_number="${{ github.event.pull_request.number }}"
+          elif [[ "${GITHUB_EVENT_NAME}" == "push" ]]; then
+            pr_number="${{ steps.get_pr_number.outputs.pr }}"
+          else
+            echo "Unexpected github event name ${GITHUB_EVENT_NAME}"
+            exit 1
+          fi
+          pr_files=$(curl -sS \
+          -H "Accept: application/vnd.github+json" \
+          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
+          https://api.github.com/repos/${{ github.repository }}/pulls/${pr_number}/files \
+          | jq .[].filename \
+          | sed 's/"//g' \
+          | tr '\n' ' ')
+          echo ::set-output name=file_list::${pr_files}
 
       - name: Detect pull/push projects
         id: projects_pull_push
@@ -223,18 +246,9 @@ jobs:
           terraform_wrapper: false
 
       - name: Setup Terragrunt
-        uses: autero1/action-terragrunt@v1.2.0
-        with:
-          terragrunt_version: 0.36.1
-
-      # security best practice: use specific version of public actions (v1)
-      - name: Turnstyle
-        id: turnstyle
-        uses: softprops/turnstyle@v1
-        with:
-          same-branch-only: false
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          wget -O /usr/local/bin/terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/${TERRAGRUNT_VERSION}/terragrunt_linux_arm64
+          chmod u+x /usr/local/bin/terragrunt
 
       - name: Init
         working-directory: "${{ env.BASE_DIR }}/${{ matrix.project }}"
@@ -274,12 +288,16 @@ jobs:
           echo 'EOF' >> $GITHUB_ENV
 
       - name: Post Plan to PR
-        uses: thollander/actions-comment-pull-request@v1.5.0
-        if: ${{ (github.event_name == 'pull_request' || github.event_name == 'push') && steps.plan.outputs.exitcode == '2' }}
-        with:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        env:
           message: "${{ env.TF_PLAN_OUT }}"
           pr_number: "${{ needs.init.outputs.pr_number }}"
+        run: |
+          escaped_message=$(echo "$message" | jq -Rsa .)
+          curl -sS -X POST \
+            -H "Accept: application/vnd.github+json" \
+            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
+            "https://api.github.com/repos/${{ github.repository }}/issues/${pr_number}/comments" \
+            -d '{"body":'"${escaped_message}"'}'
 
   apply:
     needs:
@@ -320,18 +338,9 @@ jobs:
           terraform_wrapper: false
 
       - name: Setup Terragrunt
-        uses: autero1/action-terragrunt@v1.2.0
-        with:
-          terragrunt_version: 0.36.1
-
-      # security best practice: use specific version of public actions (v1)
-      - name: Turnstyle
-        id: turnstyle
-        uses: softprops/turnstyle@v1
-        with:
-          same-branch-only: false
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          wget -O /usr/local/bin/terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/${TERRAGRUNT_VERSION}/terragrunt_linux_arm64
+          chmod u+x /usr/local/bin/terragrunt
 
       - name: Init
         working-directory: "${{ env.BASE_DIR }}/${{ matrix.project }}"
