nomis: DSOS-1524: pipeline fixes (#115)
* DSOS-1524: add nomis pipeline debug

* DSOS-1524: add nomis pipeline debug

* DSOS-1524: tweak nomis PR steps

* DSOS-1524: dummy change to test pipeline

* DSOS-1524: pipeline tweak to allow testing on push in branch

* DSOS-1524: run curl silently to improve output

* DSOS-1524: temporarily disable pull trigger

* DSOS-1524: temporarily disable pull trigger

* DSOS-1524: undo testing

* DSOS-1524: undo testing

* DSOS-1524: typo

diff --git a/.github/workflows/nomis.yml b/.github/workflows/nomis.yml
--- a/.github/workflows/nomis.yml
+++ b/.github/workflows/nomis.yml
@@ -73,15 +73,20 @@ jobs:
       - name: Checkout the code
         uses: actions/checkout@v3.1.0
 
-      # get PR number on push
+      # get PR number: for posting PR comments and figuring out changed files
       - name: Get PR number on push
         id: get_pr_number
+        if: ${{ github.event_name == 'push' }}
         run: |
-          pr_number=$(curl \
+          pr_number=$(curl -sS \
             -H "Accept: application/vnd.github+json" \
             -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
-            https://api.github.com/repos/${{ github.repository }}/commits/${{ github.head_ref }}/pulls \
+            https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/pulls \
             | jq -r '.[0].number')
+          if [[ $pr_number == "null" ]]; then
+            echo "Could not find PR number for commit=${{ github.sha }}"
+            exit 1
+          fi
           echo ::set-output name=pr::${pr_number}
 
       # for workflow dispatch, check valid project specified
@@ -115,10 +120,18 @@ jobs:
         id: files
         if: ${{ github.event_name == 'pull_request' || github.event_name == 'push' }}
         run: |
-          pr_files=$(curl \
+          if [[ "${GITHUB_EVENT_NAME}" == "pull_request" ]]; then
+            pr_number="${{ github.event.pull_request.number }}"
+          elif [[ "${GITHUB_EVENT_NAME}" == "push" ]]; then
+            pr_number="${{ steps.get_pr_number.outputs.pr }}"
+          else
+            echo "Unexpected github event name ${GITHUB_EVENT_NAME}"
+            exit 1
+          fi
+          pr_files=$(curl -sS \
           -H "Accept: application/vnd.github+json" \
           -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
-          https://api.github.com/repos/${{ github.repository }}/pulls/${{ steps.get_pr_number.outputs.pr }}/files \
+          https://api.github.com/repos/${{ github.repository }}/pulls/${pr_number}/files \
           | jq .[].filename \
           | sed 's/"//g' \
           | tr '\n' ' ')
